# -*- coding: utf-8 -*-
"""TrabajoFinal_0.1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mxanMcbZbpLZzX-Yff6sRcdVRrAl3UML
"""

class Unidad:
  def __init__(self, c_name, c_dir, p_name, p_dir, p_cost, m_name, m_num): #constructor
    self.c_name = c_name
    self.c_dir = c_dir
    self.p_name = p_name
    self.p_dir = p_dir
    self.p_cost = p_cost
    self.m_name = m_name
    self.m_num = m_num

def imprimir_lista(lista):
  for i in range(0, len(lista)):
    print("------------------------------------------------")
    print(" EMPRESA: ", lista[i].c_name)
    print("------------------------------------------------")
    print(" Dirección de la empresa: ", lista[i].c_dir)
    print(" Nombre del proyecto: ", lista[i].p_name)
    print(" Locación del proyecto: ", lista[i].p_dir)
    print(" Costo del proyecto: ", lista[i].p_cost)
    print(" Mineral a extraer: ", lista[i].m_name)
    print(" Cantidad del mineral: ", lista[i].m_num)
    print("------------------------------------------------")

def acceso_unidades(lista):
  print("-----------------------------------------------------------")
  print("A continuación las unidades con sus respectivas empresas")
  print("----------------------------------------------------------")
  imprimir_lista(lista)

def agregar_unidad():
  print("---------------------------------")
  print("Complete las siguientes preguntas")
  print("---------------------------------")
  print("¿Cual es el nombre de la empresa?")
  company_name = str(input())
  print("¿Cual es la direccion de la empresa?")
  company_dir = str(input())
  print("¿Cual es el nombre del proyecto?")
  project_name = str(input())
  print("¿En que locación se hace el proyecto?")
  project_dir = str(input())
  print("¿Cual es el costo del proyecto? (respuesta en nuevos soles)")
  project_cost = int(input())
  print("¿Cual es el mineral a obtener?")
  mine_name = str(input())
  print("¿Cuanto mineral se desea extraer? (respuesta en kg)")
  mine_num = int(input())

  unidad_x = Unidad(company_name, company_dir, project_name, project_dir, project_cost, mine_name, mine_num)
  print("---------------------------------")
  print("       Unidad guardada")
  return unidad_x


def menu_ingreso():

  lista_unidades = []
  num_opcion = 0

  while num_opcion != 3:
    print("--------------------------------") #Posible bucle while num_opcion != 3
    print("      Menu_de_Ingreso")
    print("--------------------------------")
    print("1. Acceso e informe de unidades")
    print("2. Agregar una unidad (proyecto)")
    print("3. Salir")
    print("--------------------------------")

    num_opcion = int(input("Seleccione un numero: "))
    if num_opcion == 1:
      acceso_unidades(lista_unidades)

    if num_opcion == 2:
      lista_unidades.append(agregar_unidad())

  print("Progama finalizado.¡Vuelva pronto!")




#Se supone que el menu principal debería ser un bucle que sale cuando se elige 3
menu_ingreso()