# -*- coding: utf-8 -*-
"""TrabajoFinal 1.0.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n9qlL37J-n12poeqpcvLQFH3Wg9svBHG
"""

# LOGIN DNI y Registro --
# TOTAL DE PROYECTOS POR EMPRESA (Totalidad DashBoard) ---
# LLENAR ARREGLO
# GITHUB ---
# .-.-.--.EXTRA.-.--.-.-..-.
# ALGORITMO BUSQUEDA Y ORDEN
# ---------------------------
# El presente trabajo es el resultado del trabajo investigativo y resolutivo en conjunto de los estudiantes del Grupo 1


class Unidad:
  def __init__(self, c_name, c_dir, p_name, p_dir, p_cost, m_name, m_num): #constructor
    self.c_name = c_name
    self.c_dir = c_dir
    self.p_name = p_name
    self.p_dir = p_dir
    self.p_cost = p_cost
    self.m_name = m_name
    self.m_num = m_num

def ingresar_cuenta(users_lists, passwords_lists):
    verificacion = False
    print("")
    print("┌" + "─" * 40 + "┐")
    print("│{:^40}│".format("SISTEMA DE REGISTRO DE MINSUR"))
    print("├" + "─" * 40 + "┤")
    print("│{:^40}│".format("Ingrese sus credenciales."))
    print("└" + "─" * 40 + "┘")

    while verificacion == False:
      id = int(input("DNI: "))
      password = str(input("Contraseña: "))

      for i in range(len(users_lists)):
        # print(i)
        # print(id)
        # print(password)
        # print(users_lists[i])
        # print(passwords_lists[i])
        if id == users_lists[i] and password == passwords_lists[i]:
          verificacion = True

      if verificacion == True:
        print("┌" + "─" * 40 + "┐")
        print("│{:^40}│".format("Verificación completa, usuario válido"))
        print("└" + "─" * 40 + "┘")
      else:
        print("┌" + "─" * 40 + "┐")
        print("│{:^40}│".format("Usuario no registrado, intente de nuevo"))
        print("└" + "─" * 40 + "┘")

def crear_cuenta(users_lists, passwords_lists):    #Podríamos agregar una base de datos con el DNI de los trabajadores en esta parte
    id = 100000000
    while id > 99999999 or id < 9999999:           #Se verifica que el DNI sea de 8 dígitos
      print("")
      print("┌" + "─" * 40 + "┐")
      print("│{:^40}│".format("Ingrese los datos a registrar"))
      print("└" + "─" * 40 + "┘")
      
      id = int(input("DNI: "))
      password = str(input("Contraseña: "))

      if id > 99999999 or id < 9999999:
        print("┌" + "─" * 40 + "┐")
        print("│{:^40}│".format("DNI NO VALIDO. INTENTE NUEVAMENTE"))
        print("└" + "─" * 40 + "┘")

    users_lists.append(id)
    passwords_lists.append(password)
    print("┌" + "─" * 40 + "┐")
    print("│{:^40}│".format("Datos registrados correctamente"))
    print("└" + "─" * 40 + "┘")


def pantalla_login(): #Lo primero en mostrarse
    usuarios_lista = [12345678]
    contrasenas_lista = ["12345"]

    op = 0

    while op != 1:

      print("┌" + "─" * 40 + "┐")
      print("│{:^40}│".format("¿Tiene una cuenta en la plataforma?"))
      print("├" + "─" * 40 + "┤")
      print("│{:^40}│".format("1. Sí, tengo una cuenta registrada."))
      print("│{:^40}│".format("2. No, crear una una nueva cuenta."))
      print("└" + "─" * 40 + "┘")

      op = int(input("Selecciona una opción: "))

      if op == 2:
        crear_cuenta(usuarios_lista, contrasenas_lista)

    ingresar_cuenta(usuarios_lista, contrasenas_lista)

def calculo_mineral(lista, i): #Se realiza el cálculo del mineral y se devuelve la cantidad de dinero esperado segun el valor del mercado actual
    mineral = lista[i].m_name
    multiplicador = 0

    #Todos se encuentran en relacion al kilogramos, fuentes https://www.exchange-rates.org
    if mineral == "Cobre":
      multiplicador = 39.76
    if mineral == "Oro":
      multiplicador = 159538.8
    if mineral == "Plata":
      multiplicador = 4404
    if mineral == "prueba_admin":    # Simple prueba para comprobar que la variable funcione correctamente
      multiplicador = 2

    return (lista[i].m_num * multiplicador)

def imprimir_lista(lista):#Se imprime la lista y se obtiene el cálculo de ganancia

  for i in range(0, len(lista)):
    print("┌" + "─" * 80 + "┐")
    print("│{:^80}│".format(f"EMPRESA: {lista[i].c_name}"))
    print("├" + "─" * 80 + "┤")
    print("│{:^80}│".format(f"Dirección de la empresa: {lista[i].c_dir}"))
    print("│{:^80}│".format(f"Nombre del proyecto: {lista[i].p_name}"))
    print("│{:^80}│".format(f"Locación del proyecto: {lista[i].p_dir}"))
    print("│{:^80}│".format(f"Costo del proyecto: {lista[i].p_cost} Nuevos soles"))
    print("│{:^80}│".format(f"Mineral a extraer: {lista[i].m_name}"))
    print("│{:^80}│".format(f"Cantidad del mineral: {lista[i].m_num} Kg"))
    print("│{:^80}│".format(f"Expectativa de ganancia calculada: {calculo_mineral(lista, i)} Nuevos soles"))
    print("└" + "─" * 80 + "┘")
    print("")

def acceso_unidades(lista):
  print("")
  print("┌" + "─" * 80 + "┐")
  print("│{:^80}│".format("INFORME DE LAS UNIDADES"))
  
  imprimir_lista(lista)

def agregar_unidad():
  print("")
  print("┌" + "─" * 40 + "┐")
  print("│{:^40}│".format("Complete las siguientes preguntas"))
  print("└" + "─" * 40 + "┘")
  print("¿Cual es el nombre de la empresa?")
  company_name = str(input())
  print("¿Cual es la direccion de la empresa?")
  company_dir = str(input())
  print("¿Cual es el nombre del proyecto?")
  project_name = str(input())
  print("¿En que locación se hace el proyecto?")
  project_dir = str(input())
  print("¿Cual es el costo del proyecto? (Respuesta en nuevos soles)")
  project_cost = int(input())
  print("¿Cual es el mineral a obtener? (Plata, Cobre u Oro)")
  mine_name = str(input())
  print("¿Cuanto mineral se desea extraer? (Respuesta en kilogramos)")
  mine_num = int(input())

  unidad_x = Unidad(company_name, company_dir, project_name, project_dir, project_cost, mine_name, mine_num)
  
  print("┌" + "─" * 40 + "┐")
  print("│{:^40}│".format("Unidad guardada"))
  print("└" + "─" * 40 + "┘")
  return unidad_x

def buscar_unidad_por_empresa(lista_unidades):
  print("")
  print("┌" + "─" * 80 + "┐")
  print("│{:^80}│".format("BUSCADOR DE UNIDADES POR NOMBRE DE EMPRESA"))
  print("└" + "─" * 80 + "┘")
  
  nombre_busqueda = input("Ingrese el nombre de la empresa a buscar: ")

  encontrada = False
  for unidad in lista_unidades:
    if unidad.c_name.lower() == nombre_busqueda.lower():
      encontrada = True
      print("")
      print("┌" + "─" * 80 + "┐")
      print("│{:^80}│".format(f"EMPRESA: {unidad.c_name}"))
      print("├" + "─" * 80 + "┤")
      print("│{:^80}│".format(f"Dirección de la empresa: {unidad.c_dir}"))
      print("│{:^80}│".format(f"Nombre del proyecto: {unidad.p_name}"))
      print("│{:^80}│".format(f"Locación del proyecto: {unidad.p_dir}"))
      print("│{:^80}│".format(f"Costo del proyecto: {unidad.p_cost} Nuevos soles"))
      print("│{:^80}│".format(f"Mineral a extraer: {unidad.m_name}"))
      print("│{:^80}│".format(f"Cantidad del mineral: {unidad.m_num} Kg"))
      print("│{:^80}│".format(f"Expectativa de ganancia calculada: {calculo_mineral([unidad], 0)} Nuevos soles"))
      print("└" + "─" * 80 + "┘")
      print("")

  if encontrada == False:
    print("┌" + "─" * 40 + "┐")
    print("│{:^80}│".format("No se encontraron unidades con ese nombre."))
    print("└" + "─" * 40 + "┘")

def menu_ingreso():
  

  unidad_ejemplo_01 = Unidad("AyacuchoMinas", "Ayacucho", "Extracción Colpa", "Colpa", 2000000, "Oro", 10000)
  unidad_ejemplo_02 = Unidad("Minery Inc.", "New Mexico", "Project White", "Ancash", 2000000, "Plata", 500000)

  lista_unidades = [unidad_ejemplo_01, unidad_ejemplo_02] #Arreglo de trabajos/proyectos/unidades. Arreglo de objetos

  lista_usuarios_propietarios = [lista_unidades] #Arreglo de arreglos. Esta parte será usada para poder guardar las empresas y proyectos en cada usuario separado

  num_opcion = 0

  while num_opcion != 4:
    print("")
    print("┌" + "─" * 40 + "┐")
    print("│{:^40}│".format("MENÚ DE INGRESO"))
    print("├" + "─" * 40 + "┤")
    print("│{:^40}│".format("1. Acceso e informe de unidades"))
    print("│{:^40}│".format("2. Agregar una unidad (proyecto)"))
    print("│{:^40}│".format("3. Buscar unidades por empresa"))
    print("│{:^40}│".format("4. Salir"))
    print("└" + "─" * 40 + "┘")

    num_opcion = int(input("Seleccione un numero: "))
    if num_opcion == 1:
      acceso_unidades(lista_unidades)

    if num_opcion == 2:
      lista_unidades.append(agregar_unidad())
      
    if num_opcion == 3:
      buscar_unidad_por_empresa(lista_unidades)

  print("")
  print("┌" + "─" * 80 + "┐")
  print("│{:^80}│".format("Progama finalizado.¡Vuelva pronto!"))
  print("└" + "─" * 80 + "┘")

def main():

  pantalla_login()
  menu_ingreso()

#Se supone que el menu principal debería ser un bucle que sale cuando se elige 3

main()
